# Generated by Django 4.1.7 on 2023-03-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='delivery_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PICKED_UP', 'PICKED_UP'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=20),
        ),
    ]
