# Generated by Django 4.1.7 on 2023-03-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('RECIPIENT', 'RECIPIENT'), ('ADMIN', 'ADMIN'), ('CANCELLED', 'CANCELLED')], max_length=50),
        ),
    ]
